config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  get 'forecasts/result/:id', to: 'forecasts#result',as: 'forecasts_result'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  require 'json'
    def result
      File.open("./lib/pre_result_free001.json") {|file|
      @forecasts = JSON.load(file)}
      @icon = @forecasts["info"]["images"]["icon"]
      @icon2 = @forecasts["info"]["images"]["icon_s"]
      @profile = Profile.find(params[:id])

      @forecastsName = @forecasts["info"]["caption"]
      
      # forture_api 186行目
      @result = FortuneAPI::get_result('KSK', 'free001', @profile, nil).get_data
      
      @resultTitle = @result["items"][0]["caption"]
      @resultBody = @result["items"][0]["body"]
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  require 'json'
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    # ここから占い内容表示
    File.open("./lib/pre_result_free001.json") {|file|
      @forecasts = JSON.load(file)}
      @icon = @forecasts["info"]["images"]["icon"]
      @icon2 = @forecasts["info"]["images"]["icon_s"]
      @background = @forecasts["info"]["images"]["background"]
      
      @tes = FortuneAPI::get_preresult('KSK', 'free001').get_data
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end 

  def forecast
    render :template => 'forecast_controller.rb/result'
  end
  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:lastNameKana, :firstNameKana, :birthDay, :bloodType, :sex)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/forecasts/result.html.erb
<p id="notice"><%= notice %></p>
<div class="contents">
<section class="forecast">
  <div class="logo">
    <img src="<%= @icon %>">
    <img src="<%= @icon2 %>">
  </div>
  <div class="forecastText">
    <h1>占い結果</h1>
      <h3><%= @resultTitle %></h3>
        <p><%= @resultBody %></p>
  </div>
</section>
<section class="profiles">
<p>
  <strong>Lastname:</strong>
  <%= @profile.lastNameKana %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstNameKana %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthDay %>
</p>

<p>
  <strong>Bloodtype:</strong>
  <%= @profile.bloodType %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @profile.sex %>
</p>
</section>
  <%= link_to 'Edit', edit_profile_path(@profile), class: 'button' %>
  <%= link_to 'Back', profiles_path, class: 'button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lastNameKana %>
    <%= form.text_field :lastNameKana, id: :profile_lastName %>
  </div>

  <div class="field">
    <%= form.label :firstNameKana %>
    <%= form.text_field :firstNameKana, id: :profile_firstName %>
  </div>

  <div class="field">
    <%= form.label :birthDay %>
    <%= form.date_select :birthDay, :use_month_numbers => true, :start_year => 1930, id: :profile_birthDay %>
  </div>

  <div class="field">
    <%= form.label :bloodType %>
    <%= form.select :bloodType, ["A型","B型","O型","AB型"] %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <label><%= form.radio_button :sex, "men"%>Men</label>
    <label><%= form.radio_button :sex, "women"%>Woman</label>
  <div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>
<div class="contents">
<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile, class: 'button' %>
<%= link_to 'Back', profiles_path, class: 'button' %>
</div>

app/views/profiles/index.html.erb
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="/rotate.js"></script>
<p id="notice"><%= notice %></p>

<div class="contents">

<section class="forecast">
    <div class="logo1"　id="rotate">
        <figure><img src="<%= @icon %>"></figure>
    </div>
    <!--<div class="logo2"><img src="<%= @icon2 %>" id="image"></div> -->
  
  <div class="forecastText">
    <h1><%= @forecasts["info"]["name"] %></h1>
    <p><%= @forecasts["info"]["caption"] %></p>
  </div>
</section>
<section class="movie">
    <h2>日下由紀恵　出版記念セミナー</h2>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/Pqolr-wTNTw" frameborder="0" allowfullscreen></iframe>
  </section>
<section class="profiles">
<h2>占いたいプロフィールを選んでください</h2>
<h2>Profiles</h2>
<div class="table">
<table align="center">
  <thead>
    <tr>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Birthday</th>
      <th>Bloodtype</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><P><%= profile.lastNameKana %></P></td>
        <td><P><%= profile.firstNameKana %></P></td>
        <td><P><%= profile.birthDay %></P></td>
        <td><P><%= profile.bloodType %></P></td>
        <td><P><%= profile.sex %></P></td>
        <td><%= link_to 'Show', profile, class: 'button' %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile), class: 'button' %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button' %></td>
        <td><%= link_to '占う', forecasts_result_path(profile), class: 'button' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</section>
<br>
  <%= link_to 'New Profile', new_profile_path, class: 'button' %>
</div>

app/views/profiles/new.html.erb
<div class="contents">
<h1>New Profile</h1>
<p>*プロフィールはひらがなで入力ください</p>
<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path, class: 'button' %>
</div>

app/views/profiles/show.html.erb
<div class="contents">
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastNameKana %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @profile.firstNameKana %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @profile.birthDay %>
</p>

<p>
  <strong>Bloodtype:</strong>
  <%= @profile.bloodType %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @profile.sex %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile), class: 'button' %>
<%= link_to 'TOP', profiles_path, class: 'button' %>
</div>